plugins:
  group_tl_to_title_map:
    default: '{}'
    client: true
    type: text
    description: |
      配置分组+信任级别 自动分配 Title 的 JSON 映射。
      例：
      {
        "designers": ["", "Junior Designer", "Designer", "Senior Designer", "Chief Designer"],
        "developers": ["", "Junior Developer", "Developer", "Senior Developer", "Tech Lead"]
      }
